# Setup
title:               Hamid
tagline:             'Engineering the future'
description:         'I am a highly skilled and experienced software engineer with over a decade of expertise in both backend and frontend development.'
url:                 https://hamidwakili.de
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Hamid Wakili
  url:               https://hamidwakili.de
  email:             hello@hamidwakili.de

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-ZR3DK4JHR9
